export type ThemeColors = typeof Colors.light;

export function getColors(scheme: string | null | undefined): ThemeColors {
  return scheme === 'dark' ? Colors.dark : Colors.light;
}

export const Colors = {
  light: {
    bg: '#fcf8ff',
    bgMain: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceLow: '#F1F5F9',
    surfaceDim: '#E2E8F0',
    text: '#1b1b24',
    textCard: '#1e293b',
    textSecondary: '#64748b',
    textTertiary: '#94a3b8',
    border: '#E2E8F0',
    primary: '#2563EB',
    primaryHover: '#1d4ed8',
    primaryLight: '#dbeafe',
    primaryText: '#2563EB',
    danger: '#ef4444',
    dangerLight: '#fef2f2',
    dangerText: '#dc2626',
    success: '#10b981',
    successLight: '#d1fae5',
    successText: '#059669',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    warningText: '#d97706',
    accent: '#7c3aed',
    accentLight: '#ede9fe',
    indigo: '#4f46e5',
    purple: '#7c3aed',
    amber: '#f59e0b',
    emerald: '#10b981',
    tab: '#FFFFFF',
    tabActive: '#2563EB',
    tabInactive: '#94a3b8',
    card: '#FFFFFF',
    input: '#F1F5F9',
    inputBorder: '#E2E8F0',
    overlay: 'rgba(0,0,0,0.5)',
    shadow: 'rgba(0,0,0,0.05)',
    shadowMd: 'rgba(0,0,0,0.07)',
    authBg: '#fcf8ff',
    authPanelFrom: '#1b1574',
    authPanelVia: '#3525cd',
    authPanelTo: '#712ae2',
    streakFrom: '#F59E0B',
    streakTo: '#D97706',
    greenFrom: '#21c55d',
    greenTo: '#04a753',
    scoreHeaderFrom: '#1d5bc7',
    scoreHeaderVia: '#2563EB',
    scoreHeaderTo: '#4f46e5',
    levelBadgeFrom: '#2563EB',
    levelBadgeTo: '#4f46e5',
    xpFrom: '#2563EB',
    xpTo: '#4f46e5',
    achievementFrom: '#f59e0b',
    achievementTo: '#d97706',
    recommendedFrom: '#f5f3ff',
    recommendedTo: '#eff6ff',
    dashed: '#dde2e8',
  },
  dark: {
    bg: '#0a0814',
    bgMain: '#0F172A',
    surface: '#1E293B',
    surfaceLow: '#0f172a',
    surfaceDim: '#334155',
    text: '#f3effc',
    textCard: '#f1f5f9',
    textSecondary: '#94a3b8',
    textTertiary: '#64748b',
    border: 'rgba(255,255,255,0.08)',
    primary: '#3b82f6',
    primaryHover: '#60a5fa',
    primaryLight: '#1e3a5f',
    primaryText: '#60a5fa',
    danger: '#f87171',
    dangerLight: '#450a0a',
    dangerText: '#fca5a5',
    success: '#34d399',
    successLight: '#064e3b',
    successText: '#6ee7b7',
    warning: '#fbbf24',
    warningLight: '#451a03',
    warningText: '#fcd34d',
    accent: '#a78bfa',
    accentLight: '#2e1065',
    indigo: '#818cf8',
    purple: '#a78bfa',
    amber: '#fbbf24',
    emerald: '#34d399',
    tab: '#1E293B',
    tabActive: '#60a5fa',
    tabInactive: '#64748b',
    card: '#1E293B',
    input: '#0f172a',
    inputBorder: 'rgba(255,255,255,0.08)',
    overlay: 'rgba(0,0,0,0.7)',
    shadow: 'transparent',
    shadowMd: 'transparent',
    authBg: '#0a0814',
    authPanelFrom: '#1b1574',
    authPanelVia: '#3525cd',
    authPanelTo: '#712ae2',
    streakFrom: '#F59E0B',
    streakTo: '#D97706',
    greenFrom: '#21c55d',
    greenTo: '#04a753',
    scoreHeaderFrom: '#1d5bc7',
    scoreHeaderVia: '#2563EB',
    scoreHeaderTo: '#4f46e5',
    levelBadgeFrom: '#2563EB',
    levelBadgeTo: '#4f46e5',
    xpFrom: '#2563EB',
    xpTo: '#4f46e5',
    achievementFrom: '#f59e0b',
    achievementTo: '#d97706',
    recommendedFrom: '#1a0a3e',
    recommendedTo: '#0a1628',
    dashed: 'rgba(255,255,255,0.08)',
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const FontSize = {
  micro: 8,
  xs: 10,
  sm: 12,
  md: 14,
  base: 16,
  lg: 18,
  xl: 20,
  xxl: 24,
  xxxl: 30,
  hero: 36,
};

export const BorderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  card: 24,
  full: 9999,
};

export const CardStyle = {
  borderRadius: BorderRadius.card,
  borderWidth: 1,
  padding: 24,
};

export const styles = {
  bentoCard: (colors: ThemeColors) => ({
    backgroundColor: colors.surface,
    borderRadius: BorderRadius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  }),
  sectionHeader: (colors: ThemeColors) => ({
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 20,
    marginBottom: 20,
  }),
  input: (colors: ThemeColors) => ({
    width: '100%' as const,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: BorderRadius.md,
    fontSize: FontSize.md,
    color: colors.text,
  }),
  primaryButton: (colors: ThemeColors, disabled?: boolean) => ({
    backgroundColor: disabled ? colors.surfaceDim : colors.primary,
    borderRadius: BorderRadius.md,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    opacity: disabled ? 0.5 : 1,
  }),
  secondaryButton: (colors: ThemeColors) => ({
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: BorderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center' as const,
    backgroundColor: 'transparent',
  }),
  progressBar: (colors: ThemeColors) => ({
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.surfaceDim,
    overflow: 'hidden' as const,
  }),
  progressFill: (color: string, pct: number) => ({
    height: '100%' as const,
    borderRadius: 3,
    backgroundColor: color,
    width: `${Math.min(pct * 100, 100)}%`,
  }),
};
